" pathogen bundles
call pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on
set cindent
set smartindent
set autoindent
set visualbell

" Show line numbers
set number

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

set ruler
set hlsearch

set clipboard=unnamed

set background=dark
colorscheme solarized

autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p
au BufWritePost *.coffee silent CoffeeMake! -b | cwindow | redraw!
autocmd BufWritePre * :%s/\s\+$//e
