" pathogen bundles
execute pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on
set cindent
set smartindent
set autoindent
set visualbell
set incsearch

" Show line numbers
set number

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

set ruler
set hlsearch

set clipboard=unnamed

set background=dark
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
let g:solarized_termcolors = 256
colorscheme solarized

autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p
autocmd BufWritePre * :%s/\s\+$//e

let g:spec_runner_dispatcher = 'VtrSendCommandToRunner! {command}'

" Leader commands
let mapleader = ","
map <Leader>t :NERDTreeToggle<CR>
map <leader>h <esc>:call ToggleHardMode()<CR>
map <leader>r <Plug>RunFocusedSpec
map <leader>R <Plug>RunCurrentSpecFile
map <leader>e <Plug>RunMostRecentSpec

" From http://robots.thoughtbot.com/faster-grepping-in-vim
" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0

  " bind \ (backward slash) to grep shortcut
  command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
  nnoremap \ :Ag<SPACE>
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

